f_human_detection2:
  ros__parameters:
    backend: "tensorrt"
    engine_path: "yolov11m-pose.plan"
    onnx_path: "yolov11m-pose.onnx"
    input_width: 640
    precision: fp16
    input_height: 384
    conf_thr: 0.30
    iou_thr: 0.50
    max_persons: 10
    tracker_type: "byte"
    publish_overlay: false
    publish_markers: true
    sync_mode: false
    camera_frame: "camera"
