x-common: &common-setup
  build: .
  image: fabook/control:iros-0.0.6
  network_mode: host
  user: "1000:1000"
  privileged: true
  volumes:
    - ${HOME}/.Xauthority:/home/mobile/.Xauthority:rw
    - .:/home/mobile/ros2_ws/src:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev/dri:/dev/dri:rw
  environment:
    - DISPLAY
    - QT_X11_NO_MITSHM=1
  ports:
    - "9090:9090"
  working_dir: /home/mobile/ros2_ws
  entrypoint: >
    bash -lc "
      source /opt/ros/humble/setup.bash &&
      mkdir -p ~/ros2_ws/src &&
      exec bash
    "

services:
  terminal:
    <<: *common-setup
    stdin_open: true
    tty: true
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/dri:/dev/dri"
    group_add:
      - "44"
    command: []